// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCjcDxHZBsWpXUk-PfVra1peMRQCONdaA',
    appId: '1:147352333673:web:0328fb1813b1826a59a1f8',
    messagingSenderId: '147352333673',
    projectId: 'recycle-app-2b55a',
    authDomain: 'recycle-app-2b55a.firebaseapp.com',
    storageBucket: 'recycle-app-2b55a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL7LFSuDlUPKD_voDlWn0JfMveD1Sqq7Q',
    appId: '1:147352333673:android:5198a15de6051d2d59a1f8',
    messagingSenderId: '147352333673',
    projectId: 'recycle-app-2b55a',
    storageBucket: 'recycle-app-2b55a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBorkRJBQ1LUgoPecw5qJNpjBtEFooi8UA',
    appId: '1:147352333673:ios:e15617e8389ff46f59a1f8',
    messagingSenderId: '147352333673',
    projectId: 'recycle-app-2b55a',
    storageBucket: 'recycle-app-2b55a.appspot.com',
    iosClientId: '147352333673-3957sff5do7gh49e5o36s2auvdncoje1.apps.googleusercontent.com',
    iosBundleId: 'com.example.recycleApp',
  );
}
